### ISSUE TITLE
Ubuntu 16.04 - Argument `-s' is neither k=v nor k@v

### ISSUE THREAD

**Issue by TheSimpleZ** [jpmens/jo#100]
Tried running this: `jo -- -s 1=0000001 -s 2=0000003 -s 3=0000004`
Expected this :`{"1":"0000001","2":"0000003","3":"0000004"}`

On Ubuntu 18.04 it works fine.
On Ubuntu 16.04 i get this response:
```
Argument `-s' is neither k=v nor k@v
Argument `-s' is neither k=v nor k@v
Argument `-s' is neither k=v nor k@v
{"1":1,"2":3,"3":4}
```

Is there any know workaround to make it work on 16.04?

**Comment by jpmens** [comment]
Which versions of `jo` do you have on 16.04 and on 18.04? I assume they're different, and the package hasn't been updated. That is not something we do here.

**Comment by TheSimpleZ** [comment]
`jo -v` shows "jo 1.0" on both 18.04 and 16.04. So i assume it's the same version.

**Comment by gromgit** [comment]
As the author of the type-coercion code, I recall that it was a v1.1 feature, but `jo`'s internal version number was only bumped a few days after my code was merged.

@TheSimpleZ , since you say both executables report v1.0, it's very likely that:

* Ubuntu 18.04 `jo` is built from code in between the two abovementioned events
* Ubuntu 16.04 `jo` is built from code before my type-coercion addition

Therefore, the only sensible way forward is to build your `jo` from the latest source.

**Comment by TheSimpleZ** [comment]
Alright, thanks!
