### ISSUE TITLE
Appending on to existing JSON

### ISSUE THREAD

**Issue by scastria** [jpmens/jo#113]
Is there a way to use jo with multiple commands to append JSON from a previous command to the next command?  I am trying to avoid a super long single jo command line and break it up into several invocations that keep appending onto the previous output.

**Comment by jpmens** [comment]
I don’t think that’ll be possible without mucking about with assembling each of the invocations.

**Comment by scastria** [comment]
Then I would like to make this a feature request. It would be nice to invoke jo with an existing json file or input string, a command option to append, and some kind of json path to designate where to append the specified new json that follows on the command line. Thanks for a great tool.

**Comment by gromgit** [comment]
@scastria, if you're still interested in this feature, can you post a sample workflow that you envision? Basically, flesh out exactly how you'd use this feature, down to the (hypothetical) command invocations. Thanks much!

**Comment by tommyalatalo** [comment]
I second this, request.
This would be useful in order to either get json from an external source, like a curl request, and then append/insert data into that json. Another use case in scripts where it would make is much easier to build a json payload across several operations (this is what I'm doing right now, and I have to revert to jq in order to insert keys into an existing json object with a map.)

**Comment by jpmens** [comment]
Closed via #141
