### ISSUE TITLE
pulling variables from files and failing on strings with splaces.

### ISSUE THREAD

**Issue by preddyzion** [jpmens/jo#136]
Hello, 

I am trying to use jo to convert out from shell scripts to JSON objects, jo works perfectly for single strings when I have multiple words getting error out.

For example:

all_data=`cat ${LOG_FOLDER}/${BUILD_NUMBER}.txt`
 /usr/local/bin/jo -p `echo "${all_data}"`

txt file has below values:

jobId=40 osVersion="Red Hat Enterprise Linux 8.2 (Ootpa)"

I am expecting it to be 
{
jobId : 40
osVersion: "Red Hat Enterprise Linux 8.2 (Ootpa)"
}

but I get 
+ /usr/local/bin/jo -p jobId=42 'osVersion="Red' Hat Enterprise Linux 8.2 '(Ootpa)"' '"Red' Hat Enterprise Linux 8.2 '(Ootpa)"'
Argument `Hat' is neither k=v nor k@v
Argument `Enterprise' is neither k=v nor k@v
Argument `Linux' is neither k=v nor k@v
Argument `8.2' is neither k=v nor k@v
Argument `(Ootpa)"' is neither k=v nor k@v
Argument `"Red' is neither k=v nor k@v
Argument `Hat' is neither k=v nor k@v
Argument `Enterprise' is neither k=v nor k@v
Argument `Linux' is neither k=v nor k@v
Argument `8.2' is neither k=v nor k@v
Argument `(Ootpa)"' is neither k=v nor k@v
+ cat /export/appl/config/jenkins/automation/logs/getOSVersion/42.json
{
   "jobId": 42,
   "osVersion": "\"Red"
}

Greatly appreciate any help on the same.

**Comment by gromgit** [comment]
You're falling afoul of your shell's word splitting (e.g. see [the _EXPANSION_ section of the bash man page](https://man7.org/linux/man-pages/man1/bash.1.html#EXPANSION)).

For this _specific_ case, you can use `eval` to re-parse the final command string:
```
eval /usr/local/bin/jo -p "${all_data}"
```
However, since the data is coming from a log file, you really should read https://mywiki.wooledge.org/BashFAQ/048 to see how using `eval` can go disastrously wrong.

**Comment by preddyzion** [comment]
Thank you very much, that helped me out. greatly appreciate it.
