### ISSUE TITLE
Possible to run in busybox?

### ISSUE THREAD

**Issue by tanvp112** [jpmens/jo#146]
Hi, is there a binary release for busybox where we can copy into busybox image and run? I read that jo can be integrate into busybox with buildroot, but I think the standard busybox image doesn't have that.

Thanks.

**Comment by gromgit** [comment]
I'm confused about what you're actually asking for:
1. `busybox` is a single binary that incorporates the functionality of multiple (basic) programs, while `buildroot` is a tool to create bootable Linux root images that incorporates programs like `busybox`.
2. `busybox` has its own build system, that has nothing to do with `buildroot`.
3. There's no such thing as a "standard `busybox` image", since all root images that include `busybox` are necessarily customized to the hardware they're meant to be run on.
4. Some embedded root images use non-GNU system C libraries, that `jo` hasn't been tested against.

If you're asking for `jo` functionality to be incorporated into `busybox`, that requires source changes like what's described [here](http://web.archive.org/web/20201109032023/www.ibm.com/developerworks/linux/library/l-busybox/). I don't know if @jpmens wants to support that effort.

If you're asking for `jo` itself to be included in a root image via `buildroot`, that's something you'd need to do yourself, but at least that's something that may not involve source changes to `jo`.

So to answer the top-line question:
> **Possible to run in busybox?**

Probably, but you'll likely have to do the work yourself.

**Comment by tanvp112** [comment]
Too narrow in mindset can make one confused himself.

1. So? There are busybox images built with jo, in case you don't know.

2. You are confusing yourself.

3. No. Again you made assumption that busybox MUST only be used as embedded system.

4. So? Was there an question about C?

Please stop answering while you don't even understand the question, let alone trying to answer on the repo owner himself.

**Comment by gromgit** [comment]
Bottom line: Your request is not clear. At all.

And while I may not be the repo owner, I've contributed enough to core `jo` that I have proven interest in the project. If you can be more clear and less rude, I'd be happy to see what can be done.

Let's start with a simple question: What is this "standard busybox image" you're talking about, and do you have a link to it? It's not clear from your question whether by "image" you mean "prebuilt busybox binary" or "Linux root image with busybox included".

**Comment by jpmens** [comment]
@tanvp112 your tone is uncalled for, and I'd like that to quickly change here.

You seem not to have noticed that @gromgit is a **major** contributor to `jo`, and while he's maybe not the repo owner, he definitely knows what he's talking about, often more than I do.

Please answer his valid questions politely. Thank you.

**Comment by tanvp112** [comment]
Base on the response like the above who is rude? My goodness... best let readers judge for themselves. A frog in the well thought his little window is the whole world.

For anyone who reach here for similar question, try [this](https://www.google.com/search?q=busybox+jq&oq=busybox+jq&aqs=chrome..69i57j0i22i30j69i60l3.1991j0j7&sourceid=chrome&ie=UTF-8) instead.
