### ISSUE TITLE
Release binaries for different platforms

### ISSUE THREAD

**Issue by jbergstroem** [jpmens/jo#148]
It would be great if releases were made available for common platforms such as linux-glibc-amd64 as part of your release procedure. I understand this might add weight to release procedures, but my use-case would greatly benefit from having a ready-to-use binary available since I would invoke it from a github action. Having to pull/compile adds precious seconds to something that can be made once instead of per-ci-usage!

Would you perhaps accept a PR that would improve the release procedure to emit such binaries?

Thanks for your consideration.

**Comment by jpmens** [comment]
Good suggestion, and I would accept the PR, but I'll point out that I would not be creating the binaries unless you've some magic which runs on a single platform and cross compiles or something. I am not willing to maintain N different OS in order to accomplish this.

So, if you want to outline how you envision this to happen, I will gladly listen. (I don't want to waste your time looking at a PR which I then might not take. :-)

**Comment by jbergstroem** [comment]
> Good suggestion, and I would accept the PR, but I'll point out that I would not be creating the binaries unless you've some magic which runs on a single platform and cross compiles or something. I am not willing to maintain N different OS in order to accomplish this.

Would you accept a PR to cover 64-bit glibc linux? 😄 Would likely cover the most common usage. I guess using the vm's that github provides through actions would be low hanging fruit.

**Comment by jpmens** [comment]
Not quite sure who'll benefit from that ... Don't most people rely on packages? (Forget that: I won't do it -- been there, not enough time or inclination for it. :-)

**Comment by jbergstroem** [comment]
Fair enough! Will close then.
