### ISSUE TITLE
Nest jo in an array

### ISSUE THREAD

**Issue by gregfoletta** [jpmens/jo#173]
From the man page I can see the way to nest JSON using command substitution:

```
# jo -p foo=$(jo bar=baz) 
{
   "foo": {
      "bar": "baz"
   }
}
```

but if I want an array of objects, this doesn't work:

```
# jo -p foo[]=$(jo bar=baz)
{
   "foo": []
}
```

Am I missing something here, or is this a bug?

**Comment by gregfoletta** [comment]
Sorry, found #49 :

```
jo -p foo=$(jo -a $(jo foo=bar))     
{
   "foo": [
      {
         "foo": "bar"
      }
   ]
}
```

**Comment by gromgit** [comment]
I'm guessing your `jo` is out-of-date, because:
```
$ jo -v
jo 1.6

$ jo -p foo[]="$(jo bar=baz)"
{
   "foo": [
      {
         "bar": "baz"
      }
   ]
}
```

_Sidenote:_ It's generally safest to quote command substitutions that are used as `jo` values, as I did above. If the substituted value contains spaces, the word splitting that's done _after_ command substitution will almost certainly cause a syntax error.

**Comment by gregfoletta** [comment]
Thank you - yes I was on 1.0 (Ubuntu repo). Moved to 1.6.
