### ISSUE TITLE
Nesting with .

### ISSUE THREAD

**Issue by domoritz** [jpmens/jo#28]
I was wondering what you think about nesting with . instead of [].

For instance `a.b.c = true`

would be

``` js
{
  a: {
    b: {
      c: true
    }
  }
}
```

This would also make #27 clearer.

**Comment by jpmens** [comment]
It certainly would make things easier, but this would then no longer be possible:

```json
{"a.b.c":"blurb"}
```

Do people use object keys with dots in them?

**Comment by gromgit** [comment]
I do. Just two examples in my daily work off the top of my head:

- Lookup table of version tags (e.g. "v0.2.7r9")
- Lookup table of ticker symbols with market/exchange qualifiers (e.g. "GSK.L" vs. "GSKN.MX" vs. "GS7.BE", GlaxoSmithKline trading in three different stock exchanges).

Since `jo` is run in a shell environment, the alternative expression:
```bash
jo -p a="$(
  jo -p b="$(
    jo -p c=true
  )"
)"
```
is somewhat more verbose, but doesn't get in the way of expressing the wide variety of keys that the [JSON spec](http://www.json.org/) permits.

**Comment by domoritz** [comment]
@jpmens . could easily be escaped with a `\` or just quoted with `"` or `'`. I think the benefit of easier nesting outweighs the inconvenience for using names with .

**Comment by jpmens** [comment]
Closing this, but I would take a pull-request if anybody wants to have a go.

**Comment by gromgit** [comment]
Just submitted PR #57 to support *object paths* as keys, with configurable path delimiters, so:
```
$ ./jo -d/ -p name=Jane point[]=1 point[]=2 geo/lat=10 geo/lon=20
{
   "name": "Jane",
   "point": [
      1,
      2
   ],
   "geo": {
      "lat": 10,
      "lon": 20
   }
}
```
Without specifying path delimiter:
```
$ ./jo -p name=Jane point[]=1 point[]=2 geo/lat=10 geo/lon=20
{
   "name": "Jane",
   "point": [
      1,
      2
   ],
   "geo/lat": 10,
   "geo/lon": 20
}
```
