### ISSUE TITLE
jo should exit quickly if issued no commands

### ISSUE THREAD

**Issue by aparks5** [jpmens/jo#88]
if jo has no commands entered it hangs. it should exit quickly.
for example in BASH we accomplish this with
```
if [ -z $1 ]; then
      (usage message)
      exit 1 # or other error code
fi
```
but in C we do something like `return false`; in `main()` or 
`exit(EXIT_SUCCESS);` with `#include <stdlib.h>`

see also: https://github.com/jpmens/jo/issues/38

**Comment by jpmens** [comment]
I recomend you place double quotes around `$1` in your shell fragment....

Other than that, `jo` is reading _stdin_, and it's not hanging:

```bash
$ echo name=Jane | jo
{"name":"Jane"}
```

**Comment by aparks5** [comment]
You can also check if stdin is empty! If you need help I can spare some cycles to address this...it does make things a little easier.

**Comment by jpmens** [comment]
Please don't; not before cat(1) does it.

**Comment by fcambus** [comment]
The fact that jo reads from stdin by default is one of it's hidden killer feature.

I used to invoke cat(1) with no argument when I leave my desk, so my cat can walk on the keyboard without risking issuing possibly dangerous arbitrary commands. Since jo came out, I use it instead, as it's one character less to type.

Please do not change this behavior.
